import puppeteer from 'puppeteer'
import { env } from '../config.js'
import type { BreakdownRow } from './usage.js'
import { formatUsd, moneyUsd, sumUsd } from '../utils/money.js'

export type StatementData = {
  agencyName: string
  clientName: string
  periodLabel: string
  rows: BreakdownRow[]
  totalUsd: number
  requestCount: number
}

export function buildStatementHtml(data: StatementData): string {
  const rows = data.rows
    .map(
      (r) => `
      <tr>
        <td>${escapeHtml(r.name)}</td>
        <td class="num">${r.requests.toLocaleString()}</td>
        <td class="num">$${formatUsd(r.costUsd)}</td>
      </tr>`,
    )
    .join('')

  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    @page { size: Letter; margin: 0.7in; }
    body {
      font-family: "IBM Plex Sans", Helvetica, Arial, sans-serif;
      color: #181816;
      margin: 0;
    }
    h1 {
      font-family: Georgia, "IBM Plex Serif", serif;
      font-style: italic;
      font-size: 28px;
      margin: 0 0 4px;
      letter-spacing: -0.02em;
    }
    .eyebrow {
      font-family: "IBM Plex Mono", monospace;
      font-size: 10px;
      letter-spacing: 0.16em;
      text-transform: uppercase;
      color: #777265;
      margin-bottom: 18px;
    }
    .meta {
      display: flex;
      justify-content: space-between;
      border-top: 1px solid #d8d3c5;
      border-bottom: 1px solid #d8d3c5;
      padding: 14px 0;
      margin: 18px 0 28px;
      font-size: 13px;
    }
    .meta strong { display: block; font-size: 11px; color: #777265; font-weight: 500; margin-bottom: 4px; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; }
    th {
      text-align: left;
      font-family: "IBM Plex Mono", monospace;
      font-size: 10px;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: #777265;
      border-bottom: 1px solid #d8d3c5;
      padding: 8px 0;
    }
    td { padding: 12px 0; border-bottom: 1px solid #ece8dc; }
    .num { text-align: right; font-variant-numeric: tabular-nums; }
    .total {
      display: flex;
      justify-content: space-between;
      margin-top: 18px;
      padding-top: 14px;
      border-top: 2px solid #181816;
      font-size: 15px;
      font-weight: 600;
    }
    footer {
      margin-top: 48px;
      font-family: "IBM Plex Mono", monospace;
      font-size: 10px;
      color: #8b8577;
      letter-spacing: 0.04em;
    }
  </style>
</head>
<body>
  <div class="eyebrow">${escapeHtml(data.agencyName)}</div>
  <h1>Client usage statement</h1>
  <div class="meta">
    <div><strong>Client</strong>${escapeHtml(data.clientName)}</div>
    <div><strong>Period</strong>${escapeHtml(data.periodLabel)}</div>
    <div><strong>Requests</strong>${data.requestCount.toLocaleString()}</div>
  </div>
  <table>
    <thead>
      <tr>
        <th>Provider</th>
        <th class="num">Requests</th>
        <th class="num">Cost (USD)</th>
      </tr>
    </thead>
    <tbody>
      ${rows || `<tr><td colspan="3">No usage in this period.</td></tr>`}
    </tbody>
  </table>
  <div class="total">
    <span>Total metered cost</span>
    <span>$${formatUsd(data.totalUsd)}</span>
  </div>
  <footer>
    Generated by Mandate · ${data.requestCount.toLocaleString()} calls attested · costs are provider list prices metered at request time
  </footer>
</body>
</html>`
}

function escapeHtml(s: string): string {
  return s
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
}

export function buildStatementCsv(data: StatementData): string {
  const lines = ['provider,requests,cost_usd']
  for (const r of data.rows) {
    lines.push(`${csvEscape(r.name)},${r.requests},${formatUsd(r.costUsd, 6)}`)
  }
  lines.push(`TOTAL,${data.requestCount},${formatUsd(data.totalUsd, 6)}`)
  return lines.join('\n') + '\n'
}

function csvEscape(value: string): string {
  if (/[",\n]/.test(value)) return `"${value.replaceAll('"', '""')}"`
  return value
}

export async function renderStatementPdf(data: StatementData): Promise<Buffer> {
  const html = buildStatementHtml(data)
  const browser = await puppeteer.launch({
    headless: true,
    executablePath: env.PUPPETEER_EXECUTABLE_PATH || undefined,
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
  })
  try {
    const page = await browser.newPage()
    await page.setContent(html, { waitUntil: 'load' })
    const pdf = await page.pdf({
      format: 'Letter',
      printBackground: true,
      margin: { top: '0.6in', right: '0.6in', bottom: '0.6in', left: '0.6in' },
    })
    return Buffer.from(pdf)
  } finally {
    await browser.close()
  }
}

export function aggregateStatement(
  agencyName: string,
  clientName: string,
  periodLabel: string,
  rows: BreakdownRow[],
): StatementData {
  const requestCount = rows.reduce((n, r) => n + r.requests, 0)
  const totalUsd = moneyUsd(sumUsd(rows.map((r) => r.costUsd)))
  return { agencyName, clientName, periodLabel, rows, totalUsd, requestCount }
}
